### ISSUE TITLE
`readFileSync` Not Working as Expected when using `Fetch` Backend

### ISSUE THREAD

**Issue by hawav** [zen-fs/core#61]
**`@zenfs/core` versions**: 0.11.2, 0.12.0

#### Expected Behavior:

The `readFileSync` function should be able to fetch the content of `test.txt` from the remote server, just like the `readFile` function does.

#### Actual Behavior:

The `readFileSync` function throws an `ENOENT` error, indicating that it cannot find the file, which is not true.

#### Steps to Reproduce:

1. Created a file `test.txt` in the directory with the content "Hello ZenFS!"

```bash
echo "Hello ZenFS!" > test.txt
```

2. Generated the index file using the `make-index` script from ZenFS.

```bash
npx -p @zenfs/core make-index . -o index.json
```

3. Started an HTTP file server using `serve` on port 8080 with CORS enabled.

```bash
serve . -p 8080 --cors
```

4. Configured ZenFS to use the `Fetch` Backend, pointing to the local server.

```typescript
import * as zenfs from '@zenfs/core'

await zenfs.configure({
    backend: zenfs.Fetch,
    baseUrl: '//localhost:8080',
    index: '//localhost:8080/index.json'
});
```

5. Used the `readFile` function to successfully fetch test.txt from the remote server.

```typescript
zenfs.readFile('test.txt', (e, content) => console.log(content?.toString()));
```

6. Attempted to use the readFileSync function, but encountered an error.

```typescript
console.log(zenfs.readFileSync('test.txt'));  
// Error: ENOENT: No such file or directory, '/test.txt'
```

**Comment by dr-vortex** [comment]
Okay, I've successfully reproduced the issue. I can confirm `AsyncFS.crossCopy` is not even called, so I believe that is the issue.

**Comment by dr-vortex** [comment]
@hawav This should be fixed in [v0.12.0](https://github.com/zen-fs/core/releases/tag/v0.12.0). Can you please test it with your use case, to make sure? Thanks!

- JP

**Comment by hawav** [comment]
@dr-vortex Unfortunately, the issue still persists in v0.12.0. I've verified that I'm using the correct version, and after reproducing the issue again, I can confirm that the `readFileSync` function is not working as expected.

**Comment by dr-vortex** [comment]
@hawav Could you provide a complete stack trace of the error message? (Please copy and paste into a code block).

**Comment by hawav** [comment]
@dr-vortex Here is the complete stack trace of the error message:

```
Uncaught Error: ENOENT: No such file or directory, '/test.txt'
    ErrnoError error.js:261
    With error.js:249
    _openSync sync.js:113
    _readFileSync sync.js:165
    readFileSync sync.js:184
    EditorWindow page.tsx:27
    basicStateReducer react-dom.development.js:11517
    updateReducerImpl react-dom.development.js:11737
    updateReducer react-dom.development.js:11551
    updateState react-dom.development.js:12093
    useState react-dom.development.js:13592
    useState react.development.js:2508
    EditorWindow page.tsx:12
    renderWithHooks react-dom.development.js:11121
    updateFunctionComponent react-dom.development.js:16290
    beginWork$1 react-dom.development.js:18472
    callCallback react-dom.development.js:20565
    invokeGuardedCallbackImpl react-dom.development.js:20614
    invokeGuardedCallback react-dom.development.js:20689
    beginWork react-dom.development.js:26949
    performUnitOfWork react-dom.development.js:25748
    workLoopSync react-dom.development.js:25464
    renderRootSync react-dom.development.js:25419
    performConcurrentWorkOnRoot react-dom.development.js:24504
    workLoop scheduler.development.js:256
    flushWork scheduler.development.js:225
    performWorkUntilDeadline scheduler.development.js:534
    EventHandlerNonNull* scheduler.development.js:569
    <anonymous> scheduler.development.js:630
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    <anonymous> react-dom.development.js:27
    <anonymous> react-dom.development.js:38595
    NextJS 4
    <anonymous> index.js:37
    NextJS 4
    <anonymous> client.js:3
    NextJS 4
    <anonymous> app-index.js:15
    NextJS 4
    <anonymous> app-next-dev.ts:7
    appBootstrap app-bootstrap.ts:61
    loadScriptsInSequence app-bootstrap.ts:20
    appBootstrap app-bootstrap.ts:60
    <anonymous> app-next-dev.ts:6
    NextJS 7
        js
        factory
        __webpack_require__
        __webpack_exec__
        <anonymous>
        webpackJsonpCallback
        <anonymous>
```

**Comment by dr-vortex** [comment]
I hope you don't mind, I truncated the stack trace you provided to the part relevant to ZenFS.

In any case, could you please make this change to the dist/emulation/sync.js file:
```diff
@@ -100,6 +100,7 @@ function _openSync(_path, _flag, _mode, resolveSymlinks = true) {
         stats = wrap('statSync', resolveSymlinks, path, cred);
     }
     catch (e) {
+		debugger;
         // File does not exist.
         switch (pathNotExistsAction(flag)) {
             case ActionType.CREATE:
```

Then comment with `e` (the error being caught)?

**Comment by hawav** [comment]
Of course, here is the content of `e`:

```
Error: ENOENT: No such file or directory, '/test.txt'
    ErrnoError error.js:261
    With error.js:249
    _findINodeSync fs.js:454
    findINodeSync fs.js:474
    statSync fs.js:204
    wrap sync.js:15
    _openSync sync.js:100
    _readFileSync sync.js:165
    readFileSync sync.js:184
```

**Comment by dr-vortex** [comment]
@hawav [0.12.1](https://github.com/zen-fs/core/releases/tag/v0.12.1) made some changes. I doubt it fixed the issue, but could you check anyway? Also, could you provide an updated stack trace? You won't need to make any changes or open the debugger since `_open` and `_openSync` correctly throw errors.

**Comment by hawav** [comment]
After upgrading to version 0.12.1 of `@zenfs/core`, I encountered an error with the message `EINVAL: Index version mismatch`. This error suggests that there might be a mismatch in the index version between the older and newer versions of the library.

To resolve this issue, I regenerated the `index.json` file using the latest version of `@zenfs/core` with the following command:

```bash
npx -p @zenfs/core@0.12.1 make-index . -o index.json
```

After executing this command, the error was resolved, and I was able to successfully retrieve the content of the file, which reads "Hello ZenFS!".

Since I've confirmed that the issue has been resolved, I'm going to close this issue.

If this issue persists for other users, it might be worth investigating the version compatibility between the older and newer versions of the `index.json` format in `@zenfs/core`.

Thank you for your attention to this matter!

**Comment by dr-vortex** [comment]
@hawav In hindsight, I believe your index.json may have been invalid for 0.11.*. This would explain why the issue was fixed on my side but not on yours.

0.12.0 did change the index.json format to use versioning, and to store the entries in a different way which actually keeps track of stats.
